#!/bin/bash

# Directorio del script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Nombre del entorno virtual
VENV_DIR="$SCRIPT_DIR/venv"

# Comprobar si el entorno virtual ya existe
if [ ! -d "$VENV_DIR" ]; then
    echo "Creando entorno virtual..."
    python3 -m venv $VENV_DIR
fi

# Activar el entorno virtual
source $VENV_DIR/bin/activate

# Comprobar e instalar las dependencias si no están instaladas
pip freeze | grep -q python-dotenv || pip install python-dotenv
pip freeze | grep -q pyTelegramBotAPI || pip install pyTelegramBotAPI

# Ejecutar el script de Python
python "$SCRIPT_DIR/botsend.py" "$@"
