#!/bin/bash
cd "$(dirname "$0")"

# Texto a decir
if [ -z "$*" ]; then
  # Leer todo el input desde stdin si no hay argumentos
  TEXT=$(cat)
else
  TEXT="$*"
fi

# Generar el audio
TMP_AUDIO=`./tospeech --message="$TEXT"`

if [ ! -f "$TMP_AUDIO" ]; then
  echo "Error generando audio"
  exit 1
fi

# Reproducir en voz alta
./playaudio "$TMP_AUDIO"
