#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
cd "$SCRIPT_DIR"

source .venv/bin/activate

mkdir -p ~/Logs/Telegrambot 2>/dev/null

while true; do
    pwd
    # /usr/bin/python3 ./bot.py 2>&1 >> log.txt
    # /home/sebas/telegrambot/bin/python3 ./bot.py 2>&1 >> log.txt
    echo -n  "=== " >> ~/Logs/Telegrambot/log.txt
    date >> ~/Logs/Telegrambot/log.txt
    .venv/bin/python3 ./bot.py 2>&1 >> log.txt
    # /home/sebas/miniconda3/bin/python3 ./bot.py 2>&1 >> log.txt
    sleep 1
done
