#!/bin/bash

# Directorio del script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$SCRIPT_DIR"

# Comprobar si el entorno virtual ya existe
if [ ! -d ".venv" ]; then
    echo "Creando entorno virtual..."
    python3 -m venv .venv
fi

# Activar el entorno virtual
source .venv/bin/activate

# Comprobar e instalar las dependencias si no están instaladas
.venv/bin/pip freeze | grep -q openai-whisper || .venv/bin/pip install openai-whisper

# Ejecutar el script de Python
.venv/bin/python3 "transcribe.py" "$@"
